config/routes.rb
Bloggy::Application.routes.draw do
  resources :tags

  resources :comments

  resources :blogs

  get "static_pages/test1"
  get "static_pages/test2"
  get "static_pages/test3"
  get "main/about_us" => "main#about_us", :as => :about_us
  get "main/contact_us" =>"main#contact_us", :as => :contact_us
  get "main/terms_of_service", :as => :terms_of_service 
  get "our_team" => "main#our_team", as: :our_team
  get "vision" => "main#vision", as: :vision

   
   root 'main#about_us'

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :comments
	has_many :tags
	validates_presence_of :title, :content
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
	validates_presence_of :name, :content
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :blog
	validates_presence_of :tag 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @tags = Tag.select(:tag).uniq
    if params[:title].blank?
      @blogs = Blog.order('id desc')
     else 
      tags = Tag.where(tag: params[:title])
     
      @blogs = []
      tags.each do |tag|
        parent_blog = tag.blog
        @blogs.push(parent_blog)
      end

      
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @comments = @blog.comments

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    @tag = Tag.new
    @tag.blog_id = @blog.id
   
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new

    @blog = Blog.find(params[:blog_id])
  end

  # GET /comments/1/edit
  def edit
    @blog = @comment.blog
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    Rails.logger.info @comment.name # shows attributes of @comment in these 3 lines...just to test
    Rails.logger.info @comment.content
    Rails.logger.info @comment.blog_id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :content, :blog_id)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def about_us
	end
	def contact_us
	end
	def terms_of_service
		@words = ["Microsoft", "dogs", "stale cat-food"]
		@color = "red"

	end
	def our_team
	end
	def vision
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def test1
  	puts "Hello, I am getting executed...for forking real!"
  end

  def test2
  end

  def test3
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new

    @tag.blog_id = params[:blog_id]

    @blog = Blog.find(params[:blog_id])
  end

  # GET /tags/1/edit
  def edit

  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to blog_path(@tag.blog_id), notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    temp_blog_id = @tag.blog_id
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to edit_blog_path(temp_blog_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tag, :blog_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/blogs/_form.html.erb
<html>
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
  <%= f.hidden_field :blog_id, :value => @blog.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</html>

app/views/blogs/edit.html.erb
<html>
<h1 style="padding:5px">Edit the Blog</h1>

<%= render 'form' %>
<div style="padding:10px">
<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %> 
</div>
<hr/>

<div>
<h3 style="padding:5px">Add a tag</h3>
<%= render 'tags/form' %>
</div>
<hr/>

<h3 style="padding:5px">Existing Tags</h3>

<<div style= "margin-top:30px;font-size:20px">
<% @blog.tags.each do |tag| %>

<span style ="background-color:gray;padding:2px;margin:4px;border-radius:5px;color:white"><%= tag.tag %></span>
<%= link_to 'x', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</div>
</html>

app/views/blogs/index.html.erb
<html>
<body>
  <% @tags.each do |tag| %>
    <span style ="padding:2px;margin:4px">
    <%= link_to tag.tag, blogs_path(title: tag.tag) %>
    </span>
  <% end %>
<div style="padding-left:20px">
  <h1><u>What People Think</u></h1>
  <div class="button">
  <%= link_to 'Let Us Know What You Think!', new_blog_path %>
  </div>
</div>
<div style="pading-left:20px;padding-bottom:50px">
  <% @blogs.each do |blog| %>
  <div>
    <hr/>
    <h2><u><%= blog.title %></u></h2>
      <% blog.tags.each do |tag| %>
        <%= link_to tag.tag, blogs_path(title: tag.tag) %>
      <% end %>
  </div>
  <div class="blog-title">
      <%= blog.content %>
  </div>
    <%= time_ago_in_words(blog.created_at)%>
  <div class="blog-control">
      <%= link_to 'Show', blog %>
      <%= link_to 'Edit', edit_blog_path(blog) %>
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/blogs/new.html.erb
<html>
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>
</html>

app/views/blogs/show.html.erb
<html>
<p id="notice"><%= notice %></p>

<div style= "margin-top:30px">
	<% @blog.tags.each do |tag| %>

	<span style ="background-color#:afcbaa;padding:2px;margin:4px"><%= tag.tag %></span>
	<% end %>
</div>
<div style="margin left:5px">
	<p>
  <strong>Title:</strong>
  	<%= @blog.title %>
	</p>

	<p>
  	<strong>Content:</strong>
  	<%= @blog.content %>
	</p>
</div>
<div style="padding:20px;background-color:#afcbaa">
	<% @comments.each do |comment|%>
	<%= comment.name %> - <%= comment.content %><br/>
	<% end%>
</div>
</html>

<%= link_to 'Add a comment', new_comment_path(:blog_id => @blog.id) %>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/comments/_form.html.erb
<html>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.hidden_field :blog_id, :value => @blog.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</html>

app/views/comments/edit.html.erb
<html>
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>
</html>

app/views/comments/index.html.erb
<html>
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Blog</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= comment.blog_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>
</html>

app/views/comments/new.html.erb
<html>
<h1>New comment</h1>
	<h3>Blog Title: <%= @blog.title %></h3>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>
</html>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Add a comment', new_comment_path(:blog_id => @blog_id) %>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<html> 
	<head>
	  <title>Kitties</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body bgcolor= "E6E6FA">
	<div class="Title"><em>EXPLORE LONDON</em>
	</div>

	<div id="menubar">
		<ul>
			<li>
				<%= link_to about_us_path do%>
					HOME
				<% end %>
			</li>
			<li>
				<%= link_to blogs_path do %>
					BLOGS
				<% end %>
			</li>
			<li>
					<%= link_to our_team_path do %>
					WHAT TO SEE
				<% end %>
			</li>
			<li>
				<%= link_to contact_us_path do %>
					CONTACT US
				<% end %>
			</li>
		  <li>
		  	<a href="http://www.catster.com/lifestyle/6-famous-authors-who-wrote-with-their-cats">
		  		GOOD READS
		  	</a>
		  </li>
		  <li>
		  	<a href="http://joythebaker.com/2012/09/chewy-cat-treats-for-cats/">
		  		RECIPES
		  	</a>
		  </li>
		  <li>
		  	<%= link_to terms_of_service_path do %>
				READ ME
				<% end %>		
		  </li>
		  <li>
		  	<a href="http://thechive.com/category/funny_hilarious_photos_pictures/cat-saturday/">
		  		PLANS FOR WORLD DOMINATION
		  	</a>
			</li>
		</ul>
	</div>

	<div id="footer">
		join us in celebrating:  
		<a href="http://felineyogi.com/yoga-tip-of-the-week/cat-world-domination-day/">
			cat world domination day
		</a>
	</div>
	<%= yield %>
	</body>
</html>

app/views/main/about_us.html.erb
<body>
<div id="background">
<%= image_tag "mind_the_gap.jpg", class: stretch" alt: "CAT WORLD DOMINATION!!!!"%>
</div>
</body>	
	    

app/views/main/contact_us.html.erb
<html>
<div class="directions">
	    <div class="pic" style:"padding:20px">CALL: 555-867-5309
	    </div>
	    <a href="http://www.hemingwayhome.com/directions/"><div style:"padding:20px">MAP & DIRECTIONS
	    </div></a>
</div>
<div class="bio">
		    <h3 class= "who"><u>WHO WE ARE</u></h3>
		        <ul>
		            <p><em>Boudreaux</em></p>
		            <ol>
		                <p>Mackerel Tabby</p>
		                <p>MO: The <em>Ankle Claw</em>.  Boo was in the FSF (Feline Special Forces...what happens in Fight Club stays in Fight Club...</p>
		            </ol>
		            <p><em>Sebastian</em></p>
		            <ol>
		                <p>Black</p>
		                <p>MO: Camouflage.  Sometimes all you can make out is a pair of glowing yellow eyes and then it's too late...</p>
		           </ol>
		           <p><em>Moriarty</em></p>
		           <ol>
		                <p>Red Tabby</p>
		                <p>MO: Chemical Warfare.  Mo has been approached by the FBI, the CIA, and the FSF for his unique CBP (cat bowel processing).</p>
		            </ol>
		            <p><em>Jigi Tortellini</em></p>
		            <ol>
		                <p>Tortoiseshell</p>
		                <p>MO: Brute Strength.  What she lacks in fine motor skills, she makes up for in pure force of acceleration...</p>
		            </ol>
		        </ul>
		</div>
</html>

app/views/main/our_team.erb
<html>
<body>
<h1><u>Things to See in London</u></h1>

	<div class="left">
		    <a href="http://en.wikipedia.org/wiki/Tabby_cat"><div class="pic">London Eye</div></a>
		    <div class="pic" id="Boo" style="height:240px;width:340px;border-radius:5px;"><img src="assets/london_eye.jpg" onmouseover="this.src='assets/Boo_lunch.jpg'" onmouseout="this.src='assets/london_eye.jpg'" style="height:240px;width:340px;border-radius:5px;"/></div>
		    <a href="http://en.wikipedia.org/wiki/Black_cat"><div class="pic">Big Ben</div></a>
		    <div class="pic" id="Seb" style="height:300px;width:240px;border-radius:5px;"><img src="assets/big_ben.jpg" onmouseover="this.src='assets/Seb_plant.jpg'" onmouseout="this.src='assets/big_ben.jpg'" style="height:300px;width:240px;border-radius:5px;"/></div>
	</div>
	<div class="right">
		    <a href="http://coveredincathair.com/content/special-something-orange-tabbies"><div class="pic">Guard at the Tower of London</div></a>
		    <div class="pic" id="Mo" style="height:300px;width:240px;border-radius:5px;"><img src="assets/guard.jpg" onmouseover="this.src='assets/Mo_light.jpg'" onmouseout="this.src='assets/guard.jpg'" style="height:300px;width:240px;border-radius:5px;"/></div>
		    <a href="http://consciouscat.net/2009/08/17/tortitude-the-unique-personality-of-tortoiseshell-cats/"><div class="pic">Catch a Show</div></a>
		    <div class="pic" id="Jig" style="height:240px;width:300px;border-radius:5px;"><img src="assets/shows.jpg" onmouseover="this.src='assets/Jigi_pretty.jpg'" onmouseout="this.src='assets/shows.jpg'" style="height:240px;width:300px;border-radius:5px;"/></div>
	</div>
	</body>
</html>

app/views/main/terms_of_service.html.erb
<html> 
	<div id= "TOS">
	<h2><u>Terms of Service and Disclaimers</u></h1></h2>
	  <p>Oh you know what? This is the terms page and our cat lawyers made us put it in; nobody’s still reading this.  I bet only about five people clicked to read the Terms in the first place – we might as well just say anything we like...</p>

		<p>AJ on floor 2 of the Grace household smells of cat litter (he snacks on it).</p>

		<p>When someone sends a funny email around the offices we have to reply with iLaughed. It’s in our job description because we got a grant from Apple for cat world domination; few people know that Tim Cook is a cat hoarder.</p>

		<p>Remember that awful rumor that 50% of people are allergic to cats? Want to know how we fixed it? We bought The Beatles. We have the surviving ones come and sing to us for scraps. We’re looking at ways to reanimate the dead ones.</p>

		<p>We faked the moon landings. Did it in 2008, then brainwashed you all to believe it happened in 1969, just because we could. If anyone finds out we’ve leaked this information, we’ll be killed. But no one will ever, ever read this.</p>
		
		<h4>By the way, these are the words you can't use in correlation with this website...</h4>
			<% @words.each do |word| %>
				<% if word == "dogs" %>
				Word: yeah!! <br/>
				<% else %>
				Word: <%= word %><br/>
				<% end %>
			<% end %>	
		</div>
</html>

app/views/main/vision.erb
<h1>Our Vision</h1>

app/views/static_pages/test1.html.erb
<p id = "my_first_paragraph" class="paragraph">
Nailing down the scattershot effect on that group is difficult, but one thing is clear: While furloughed federal employees had their back pay reinstated at the end of the 16-day shutdown, no such provision is made for contractors. Those who weren't paid during the shutdown were out of luck. Some contractors lived in limbo leading to and during the shutdown, unsure of the status of their contracts. And with the possibility of another shutdown in January, some contractors remain in that limbo.
</p>
<a href="http://www.wjla.com/articles/2013/10/government-shutdown-2013-angst-for-contractors-remains-95738.html#ixzz2ie6SuGmd">Read more</a>
<button class="show_me_button">Show me1</button>
<button class="show_me_button">Show me2</button>
<button class="show_me_button">Show me3</button>

<p>
Follow us: @ABC7News on Twitter | WJLATV on Facebook
</p>

app/views/static_pages/test2.html.erb
<h1>StaticPages#test2</h1>
<p>Find me in app/views/static_pages/test2.html.erb</p>

app/views/static_pages/test3.html.erb
<h1>StaticPages#test3</h1>
<p>Find me in app/views/static_pages/test3.html.erb</p>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %> 
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.hidden_field :blog_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>


<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>What's Been Tagged</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Blog</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.tag %></td>
        <td><%= tag.blog_id %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>
	<h3>Blog Title: <%= @blog.title %></h3>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tag.tag %>
</p>

<%= link_to 'Add a Tag', new_tag_path(:blog_id => @blog_id) %>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>